### ISSUE TITLE
Table formatting is broken

### ISSUE THREAD

**Issue by unhawkable** [burningmoth/burningmoth-chromelogger-firefox#2]
![image](https://user-images.githubusercontent.com/14310995/41591977-86ed3786-73bb-11e8-9b4c-9799d41f7148.png)

afair it worked in previous versions

**Comment by tarraccas** [comment]
Ensure that the substitution patterns are not being escaped via double percentage signs (%%) in the library you're using to encode the ChromeLogger data.

Given the following script:
`<script data-chromelogger-rows="rows">var rows = [[
	[
		"%s is a string, %d is a number, %o is an object, %cthis is styled, %%s is escaped",
		'Six',
		6,
		{ 'value': 6 },
		'color:powderblue;font-weight:bold;font-style:italic',
		'and therefore not substituted'
	]
]];</script>`

The following output should result in the web console:
![image](https://user-images.githubusercontent.com/2514361/41621188-dae914d6-73c0-11e8-8365-f7bfc2636014.png)

**Comment by tarraccas** [comment]
console.table() support has been restored as of version 1.7.1
