### ISSUE TITLE
TypeError: "window.console[args.shift(...)] is undefined"

### ISSUE THREAD

**Issue by odysseuscm** [burningmoth/burningmoth-chromelogger-firefox#5]
Version 1.7 / 1.7.1 seems to have (re)introduced a bug.

console("hello word");
console("log", "hello word");
both fail with: typeError "window.console[args.shift(...)] is undefined"

console("info", "hello word");
console("error", "hello word");
console("table", ["hello word"]);
still work

P.S. console() is my wrapper function for ChromePHP::
It's the same with ChromePhp::log("hello world")

**Comment by tarraccas** [comment]
The library you're using is passing an empty `type` value in lieu of 'log' rather than omitting it from the data. When Mozilla approves v1.7.2 it will include a check that automatically resolves invalid `type` values like this to 'log' as expected.
