### ISSUE TITLE
No output when logging null value with FireFox 60.2.2esr

### ISSUE THREAD

**Issue by dev-maniac** [burningmoth/burningmoth-chromelogger-firefox#6]
When logging a null value, no logs from this request are shown in developer console. All other types are working as expected.
Logged with e.g. ChromePHP::log(null);
In Google Chrome with "Chrome Logger" plugin, the logs - including "null" - are being shown.

**Comment by tarraccas** [comment]
Confirmed. Fixed in v1.7.3.
