### ISSUE TITLE
ChromeLogger can not install in Firefox Developer Edition 67.0b16 (64-bit)

### ISSUE THREAD

**Issue by SergioHdzReyes** [burningmoth/burningmoth-chromelogger-firefox#7]
It's imposible to install it in this version.

**Comment by tarraccas** [comment]
[Mozilla broke add-ons](https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/) and have since pushed a temporary solution in the interim that should install automatically if you have something called studies enabled. Read the aforementioned link for more info.

**Comment by SergioHdzReyes** [comment]
Oh, I'm sorry, maybe I don't investigate more.
Regards.

**Comment by tarraccas** [comment]
No problem, @SergioHdzReyes . I just happened to found out from DuckDuckGo tweeting about their add-on being broken by Mozilla.

**Comment by SergioHdzReyes** [comment]
Nice, for that I love DuckDuckGo :)
